services:
  - type: web
    name: football-iq-backend
    runtime: node
    plan: free
    rootDir: ./app/Backend
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 24.14.0
      - key: DATABASE_URL
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false
      - key: FOOTBALL_DATA_API_KEY
        sync: false
      - key: THESPORTSDB_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://football-iq-frontend.onrender.com

  - type: web
    name: football-iq-frontend
    runtime: static
    rootDir: ./app/Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://football-iq-backend.onrender.com
